"use client";

import Link from "next/link";
import { motion } from "motion/react";
import { Flame, Trophy, Zap, type LucideIcon } from "lucide-react";
import { Card, Progress } from "@/components/ui/primitives";
import { cn } from "@/lib/utils";
import type { User } from "@/types";

export function UserAvatar({ user, size = "md", className }: { user: User; size?: "sm" | "md" | "lg" | "xl"; className?: string }) { const dimensions = { sm: "h-8 w-8 text-[10px]", md: "h-10 w-10 text-xs", lg: "h-14 w-14 text-sm", xl: "h-24 w-24 text-xl" }; return <span aria-label={`${user.name} avatar`} className={cn("inline-flex shrink-0 items-center justify-center rounded-full font-bold text-white ring-2 ring-surface", dimensions[size], className)} style={{ background: user.accent }}>{user.initials}</span>; }
export function XPBar({ xp, next, level, compact = false }: { xp: number; next: number; level: number; compact?: boolean }) { const value = xp / next * 100; return <div className="w-full"><div className="mb-1.5 flex items-center justify-between text-xs"><span className="font-bold">Level {level}</span><span className="text-muted">{xp.toLocaleString()} / {next.toLocaleString()} XP</span></div><Progress value={value} className={compact ? "h-1.5" : "h-2.5"} /></div>; }
export function ProgressRing({ value, size = 116, stroke = 10, children }: { value: number; size?: number; stroke?: number; children?: React.ReactNode }) { const radius = (size - stroke) / 2; const circumference = 2 * Math.PI * radius; return <div className="relative shrink-0" style={{ width: size, height: size }}><svg className="-rotate-90" width={size} height={size} aria-hidden="true"><circle cx={size/2} cy={size/2} r={radius} fill="none" stroke="var(--surface-2)" strokeWidth={stroke} /><motion.circle cx={size/2} cy={size/2} r={radius} fill="none" stroke="var(--primary)" strokeLinecap="round" strokeWidth={stroke} strokeDasharray={circumference} initial={{ strokeDashoffset: circumference }} animate={{ strokeDashoffset: circumference * (1 - value/100) }} transition={{ duration: .6, ease: "easeOut" }} /></svg><div className="absolute inset-0 flex items-center justify-center text-center">{children ?? <strong className="text-2xl">{Math.round(value)}%</strong>}</div></div>; }
export function StreakBadge({ days, muted = false }: { days: number; muted?: boolean }) { return <span className={cn("inline-flex items-center gap-1 text-sm font-bold", muted ? "text-muted" : "text-primary")}><Flame className="h-4 w-4 fill-current" />{days} {days === 1 ? "day" : "days"}</span>; }
export function SectionHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <div className="mb-5 flex items-start justify-between gap-4"><div>{eyebrow && <div className="mb-1 text-xs font-bold uppercase tracking-[.14em] text-primary">{eyebrow}</div>}<h2 className="text-xl font-bold tracking-tight md:text-2xl">{title}</h2>{description && <p className="mt-1 max-w-2xl text-sm text-muted">{description}</p>}</div>{action}</div>; }
export function PageHeader({ title, description, action }: { title: string; description?: string; action?: React.ReactNode }) { return <header className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold tracking-[-.03em] md:text-3xl">{title}</h1>{description && <p className="mt-1 text-muted">{description}</p>}</div>{action}</header>; }
export function StatCard({ icon: Icon, label, value, note, tone = "default" }: { icon: LucideIcon; label: string; value: string; note?: string; tone?: "default" | "primary" | "success" }) { return <Card className={cn("p-4", tone === "primary" && "border-primary/25 bg-primary-soft", tone === "success" && "border-success/20 bg-success-soft")}><div className="mb-4 flex items-center justify-between"><span className="text-sm text-muted">{label}</span><Icon className={cn("h-4 w-4 text-muted", tone === "primary" && "text-primary", tone === "success" && "text-success")} /></div><div className="text-2xl font-bold">{value}</div>{note && <p className="mt-1 text-xs text-muted">{note}</p>}</Card>; }
export function EmptyState({ icon: Icon = Trophy, title, description, action }: { icon?: LucideIcon; title: string; description: string; action?: React.ReactNode }) { return <div className="card flex min-h-64 flex-col items-center justify-center p-8 text-center"><span className="mb-4 rounded-full bg-primary-soft p-4 text-primary"><Icon className="h-7 w-7" /></span><h3 className="font-bold">{title}</h3><p className="mt-1 max-w-sm text-sm text-muted">{description}</p>{action && <div className="mt-5">{action}</div>}</div>; }
export function PageSkeleton({ blocks = 5 }: { blocks?: number }) { return <div className="page-wrap animate-pulse"><div className="mb-8 h-9 w-56 rounded-lg bg-surface-2"/><div className="grid gap-4 md:grid-cols-2">{Array.from({length:blocks},(_,i)=><div key={i} className={cn("card h-44 bg-surface-2/70", i===0 && "md:col-span-2 h-64")}/>)}</div></div>; }
export function BrandMark({ compact = false, dark = false }: { compact?: boolean; dark?: boolean }) { return <Link href="/dashboard" className={cn("inline-flex items-center gap-2.5 font-bold tracking-[-.03em]", dark ? "text-white" : "text-foreground")}><span className="grid h-9 w-9 place-items-center rounded-[10px] bg-primary text-white shadow-sm"><Flame className="h-5 w-5 fill-current" /></span>{!compact && <span className="text-lg">StreakUp</span>}</Link>; }
export function LevelPill({ level }: { level: number }) { return <span className="inline-flex items-center gap-1 rounded-full bg-primary-soft px-2.5 py-1 text-xs font-bold text-primary"><Zap className="h-3.5 w-3.5 fill-current" />Level {level}</span>; }
