"use client";

import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card } from "@/components/ui/primitives";
import { weeklyActivity } from "@/data/mock-data";
import { cn } from "@/lib/utils";

export function WeeklyChart(){const [range,setRange]=useState("Week");const data=range==="Week"?weeklyActivity:Array.from({length:range==="Month"?12:10},(_,i)=>({day:range==="Month"?`W${i+1}`:`M${i+1}`,completed:3+(i%3),rate:62+((i*7)%34)}));return <Card className="p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold">Weekly Activity</h2><p className="text-xs text-muted">Completion rate across scheduled habits</p></div><div className="flex rounded-lg bg-surface-2 p-1">{["Week","Month","Year"].map(v=><button key={v} onClick={()=>setRange(v)} className={cn("rounded-md px-2.5 py-1 text-xs font-semibold",range===v&&"bg-surface text-foreground shadow-sm",range!==v&&"text-muted")}>{v}</button>)}</div></div><div className="h-[220px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{left:-20,right:4,top:8,bottom:0}}><defs><linearGradient id="activityFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--primary)" stopOpacity={.28}/><stop offset="100%" stopColor="var(--primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:12}}/><YAxis domain={[0,100]} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:11}}/><Tooltip contentStyle={{background:"var(--surface)",border:"1px solid var(--border)",borderRadius:10,fontSize:12}} formatter={(value)=>[`${value}%`,"Completion"]}/><Area type="monotone" dataKey="rate" stroke="var(--primary)" strokeWidth={2.5} fill="url(#activityFill)"/></AreaChart></ResponsiveContainer></div></Card>}

export function ConsistencyHeatmap(){const values=useMemo(()=>Array.from({length:112},(_,i)=>({value:(i*7+i%5)%6,date:new Date(Date.UTC(2026,7,18)-(111-i)*86400000).toLocaleDateString("en-US",{month:"short",day:"numeric",timeZone:"UTC"})})),[]);return <Card className="p-5"><div className="mb-5 flex items-end justify-between"><div><h2 className="font-bold">Consistency</h2><p className="text-xs text-muted">Your last 16 weeks of check-ins</p></div><div className="flex items-center gap-1 text-[10px] text-muted"><span>Less</span>{[0,1,2,3,4].map(i=><span key={i} className="h-2.5 w-2.5 rounded-[3px]" style={{background:i===0?"var(--surface-2)":`color-mix(in srgb, var(--primary) ${20+i*18}%, var(--surface))`}}/>)}<span>More</span></div></div><div className="overflow-x-auto pb-2"><div className="grid min-w-[620px] grid-flow-col grid-rows-7 gap-1" aria-label="Habit consistency heatmap">{values.map((cell,i)=><div key={i} title={`${cell.date} — ${cell.value} of 5 habits completed`} className="aspect-square min-w-2.5 rounded-[3px]" style={{background:cell.value===0?"var(--surface-2)":`color-mix(in srgb, var(--primary) ${18+cell.value*15}%, var(--surface))`}}/>)}</div></div></Card>}
