"use client";

import { useState } from "react";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input, Label, Modal, Select, Switch, Textarea } from "@/components/ui/primitives";
import { useAppStore } from "@/store/app-store";

export function ChallengeForm({open,onOpenChange}:{open:boolean;onOpenChange:(v:boolean)=>void}){const notify=useAppStore(s=>s.notify);const [title,setTitle]=useState("");const [desc,setDesc]=useState("");const [after,setAfter]=useState(true);const [visibility,setVisibility]=useState("Public");const submit=(e:React.FormEvent)=>{e.preventDefault();notify("Challenge created. Invite friends to build momentum.","success");onOpenChange(false);setTitle("");setDesc("")};return <Modal open={open} onOpenChange={onOpenChange} title="Create a challenge" description="Set a clear shared goal and give people a reason to show up."><form onSubmit={submit} className="space-y-4"><div><Label htmlFor="challenge-title">Title</Label><Input id="challenge-title" value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. 21 Days of Morning Movement" required minLength={4}/></div><div><Label htmlFor="challenge-desc">Description</Label><Textarea id="challenge-desc" value={desc} onChange={e=>setDesc(e.target.value)} placeholder="What will participants do each day?" required minLength={10}/></div><div className="grid grid-cols-2 gap-3"><div><Label>Category</Label><Select><option>Fitness</option><option>Learning</option><option>Health</option><option>Productivity</option><option>Mindfulness</option></Select></div><div><Label>Difficulty</Label><Select><option>Easy</option><option>Medium</option><option>Hard</option></Select></div></div><div className="grid grid-cols-2 gap-3"><div><Label>Start date</Label><Input type="date" defaultValue="2026-08-24"/></div><div><Label>End date</Label><Input type="date" defaultValue="2026-09-22"/></div></div><div><Label>Goal</Label><Input placeholder="20 minutes daily" required/></div><div><Label>Rules</Label><Textarea placeholder="Describe what counts as a successful daily check-in."/></div><div className="grid grid-cols-2 gap-3"><div><Label>Visibility</Label><Select value={visibility} onChange={e=>setVisibility(e.target.value)}><option>Public</option><option>Friends Only</option><option>Private / Invite Only</option></Select></div><div><Label>Participant limit</Label><Input type="number" min="2" placeholder="Optional"/></div></div><div className="flex items-center justify-between rounded-xl border p-4"><div><div className="font-semibold">Allow joining after start</div><p className="text-xs text-muted">New participants can catch up.</p></div><Switch checked={after} onCheckedChange={setAfter} label="Allow joining after start"/></div><div className="flex justify-end gap-3 border-t pt-5"><Button variant="ghost" type="button" onClick={()=>onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={title.length<4||desc.length<10}><Plus className="h-4 w-4"/>Create Challenge</Button></div></form></Modal>}
