"use client";

import Link from "next/link";
import { CalendarDays, Check, Flame, Globe2, Lock, MessageCircle, Trophy, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge, Card, Progress } from "@/components/ui/primitives";
import { DynamicIcon } from "@/components/shared/icon-map";
import { EmptyState, PageHeader, UserAvatar } from "@/components/shared/shared";
import { challengeParticipants, users } from "@/data/mock-data";
import { useAppStore } from "@/store/app-store";

export function ChallengeDetail({id}:{id:string}){const challenge=useAppStore(s=>s.challenges.find(c=>c.id===id));const toggle=useAppStore(s=>s.toggleChallenge);const activities=useAppStore(s=>s.activities);const react=useAppStore(s=>s.toggleReaction);if(!challenge)return <div className="page-wrap"><EmptyState title="This challenge is unavailable." description="It may have ended, been made private, or no longer exists." action={<Button asChild><Link href="/challenges">Browse Challenges</Link></Button>}/></div>;const creator=users.find(u=>u.id===challenge.creatorId)!;const participants=challengeParticipants.filter(p=>p.challengeId===id);return <div className="page-wrap"><PageHeader title={challenge.title} description={challenge.description} action={<Button variant={challenge.joined?"secondary":"default"} onClick={()=>toggle(id)}>{challenge.joined?<><Check className="h-4 w-4"/>Joined · Leave</>:"Join Challenge"}</Button>}/><Card className="mb-5 overflow-hidden"><div className="subtle-grid border-b border-border bg-primary-soft/60 p-6 md:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><span className="grid h-20 w-20 place-items-center rounded-2xl bg-primary text-white"><DynamicIcon name={challenge.icon} className="h-9 w-9"/></span><div className="flex-1"><div className="flex flex-wrap gap-2"><Badge>{challenge.category}</Badge><Badge>{challenge.difficulty}</Badge><Badge>{challenge.visibility==="Public"?<Globe2 className="h-3 w-3"/>:<Lock className="h-3 w-3"/>}{challenge.visibility}</Badge></div><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm text-muted"><span className="flex items-center gap-2"><CalendarDays className="h-4 w-4"/>{challenge.startDate} — {challenge.endDate}</span><span className="flex items-center gap-2"><Users className="h-4 w-4"/>{challenge.participants.toLocaleString()} participants</span></div><div className="mt-3 flex items-center gap-2 text-sm"><UserAvatar user={creator} size="sm"/><span>Created by <Link className="font-semibold hover:text-primary" href={`/profile/${creator.username}`}>{creator.name}</Link></span></div></div></div></div><div className="p-5 md:p-6"><div className="mb-2 flex items-end justify-between"><div><div className="text-xs font-bold uppercase tracking-[.12em] text-primary">Your Progress</div><div className="mt-1 text-2xl font-bold">18 / 30 days</div></div><span className="flex items-center gap-1 font-bold text-primary"><Flame className="h-4 w-4 fill-current"/>8 day challenge streak</span></div><Progress value={challenge.progress} className="h-3"/><p className="mt-3 text-sm text-muted">Goal: {challenge.goal}</p></div></Card>
  <div className="grid gap-5 lg:grid-cols-[minmax(0,1.2fr)_minmax(300px,.8fr)]"><Card className="p-5"><h2 className="font-bold">Challenge calendar</h2><p className="mb-5 text-xs text-muted">Every check-in keeps your challenge streak moving.</p><div className="grid grid-cols-7 gap-2">{Array.from({length:30},(_,i)=><div key={i} className={`grid aspect-square place-items-center rounded-lg text-xs font-semibold ${i<18?i===6?"bg-warning-soft text-warning":"bg-success-soft text-success":i===18?"border-2 border-primary text-primary":"bg-surface-2 text-muted"}`}>{i<18&&i!==6?<Check className="h-3.5 w-3.5"/>:i+1}</div>)}</div></Card><Card className="p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">Leaderboard</h2><Trophy className="h-4 w-4 text-primary"/></div><div className="space-y-2">{(participants.length?participants:[{userId:"sarah",rank:1,progress:100,streak:18},{userId:"mike",rank:2,progress:96,streak:17},{userId:"alex",rank:3,progress:93,streak:8}]).map(p=>{const u=users.find(user=>user.id===p.userId)!;return <div key={p.userId} className={`flex items-center gap-3 rounded-xl p-3 ${p.userId==="alex"?"bg-primary-soft":"bg-surface-2"}`}><strong className="w-5 text-center">{p.rank}</strong><UserAvatar user={u} size="sm"/><div className="min-w-0 flex-1"><div className="truncate font-semibold">{u.name}{p.userId==="alex"&&" (You)"}</div><div className="text-xs text-muted">{p.streak} day streak</div></div><strong>{p.progress}%</strong></div>})}</div></Card></div><Card className="mt-5 p-5"><h2 className="mb-4 font-bold">Challenge activity</h2><div className="space-y-3">{activities.slice(0,4).map(activity=>{const u=users.find(x=>x.id===activity.userId)!;return <div key={activity.id} className="flex items-start gap-3 rounded-xl border p-3"><UserAvatar user={u} size="sm"/><div className="flex-1"><p className="text-sm"><strong>{u.name}</strong> {activity.message}</p><p className="text-xs text-muted">{activity.detail}</p></div><button onClick={()=>react(activity.id,"fire")} className="rounded-lg border px-2 py-1 text-xs">🔥 {activity.reactions[0].count}</button></div>})}</div><div className="mt-4 flex items-center gap-2 rounded-xl bg-surface-2 p-3 text-sm text-muted"><MessageCircle className="h-4 w-4"/><input className="flex-1 bg-transparent outline-none" placeholder="Send a quick note of support…"/><Button size="sm">Send</Button></div></Card></div>}
