"use client";

import * as Dialog from "@radix-ui/react-dialog";
import * as Dropdown from "@radix-ui/react-dropdown-menu";
import * as SwitchPrimitive from "@radix-ui/react-switch";
import * as Tooltip from "@radix-ui/react-tooltip";
import { X } from "lucide-react";
import { cn } from "@/lib/utils";

export function Card({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("card", className)} {...props} />; }
export function Badge({ className, ...props }: React.HTMLAttributes<HTMLSpanElement>) { return <span className={cn("inline-flex items-center gap-1 rounded-full border border-border bg-surface-2 px-2.5 py-1 text-xs font-semibold text-muted", className)} {...props} />; }
export function Progress({ value, className }: { value: number; className?: string }) { return <div className={cn("h-2 overflow-hidden rounded-full bg-surface-2", className)} role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><div className="h-full rounded-full bg-primary transition-[width] duration-500" style={{ width: `${Math.min(100, Math.max(0, value))}%` }} /></div>; }
export function Input(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className={cn("h-10 w-full rounded-[10px] border border-border bg-background px-3 text-sm placeholder:text-muted/70 focus:border-primary focus:outline-none", props.className)} />; }
export function Textarea(props: React.TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea {...props} className={cn("min-h-24 w-full resize-y rounded-[10px] border border-border bg-background px-3 py-2 text-sm placeholder:text-muted/70 focus:border-primary focus:outline-none", props.className)} />; }
export function Label({ className, ...props }: React.LabelHTMLAttributes<HTMLLabelElement>) { // eslint-disable-next-line jsx-a11y/label-has-associated-control
  return <label className={cn("mb-1.5 block text-sm font-semibold", className)} {...props} />;
}
export function Select(props: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select {...props} className={cn("h-10 w-full rounded-[10px] border border-border bg-background px-3 text-sm focus:border-primary focus:outline-none", props.className)} />; }
export function Switch({ checked, onCheckedChange, label }: { checked: boolean; onCheckedChange: (checked: boolean) => void; label: string }) { return <SwitchPrimitive.Root checked={checked} onCheckedChange={onCheckedChange} aria-label={label} className="relative h-6 w-11 rounded-full bg-border transition data-[state=checked]:bg-primary"><SwitchPrimitive.Thumb className="block h-5 w-5 translate-x-0.5 rounded-full bg-white shadow transition-transform data-[state=checked]:translate-x-[22px]" /></SwitchPrimitive.Root>; }
export function AppTooltip({ label, children }: { label: string; children: React.ReactNode }) { return <Tooltip.Root><Tooltip.Trigger asChild>{children}</Tooltip.Trigger><Tooltip.Portal><Tooltip.Content side="right" className="z-[100] rounded-md bg-foreground px-2 py-1 text-xs text-background shadow-lg" sideOffset={8}>{label}<Tooltip.Arrow className="fill-foreground" /></Tooltip.Content></Tooltip.Portal></Tooltip.Root>; }
export function Modal({ open, onOpenChange, title, description, children, className }: { open: boolean; onOpenChange: (value: boolean) => void; title: string; description?: string; children: React.ReactNode; className?: string }) { return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-black/55 data-[state=open]:animate-in" /><Dialog.Content className={cn("fixed bottom-0 left-0 right-0 z-50 max-h-[92vh] overflow-y-auto rounded-t-2xl border border-border bg-surface p-5 shadow-2xl md:bottom-auto md:left-1/2 md:right-auto md:top-1/2 md:w-[min(680px,calc(100vw-32px))] md:-translate-x-1/2 md:-translate-y-1/2 md:rounded-2xl md:p-6", className)}><div className="mb-5 pr-10"><Dialog.Title className="text-xl font-bold">{title}</Dialog.Title>{description && <Dialog.Description className="mt-1 text-sm text-muted">{description}</Dialog.Description>}</div><Dialog.Close className="absolute right-4 top-4 rounded-lg p-2 text-muted hover:bg-surface-2" aria-label="Close dialog"><X className="h-4 w-4" /></Dialog.Close>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>; }
export const DropdownMenu = Dropdown.Root; export const DropdownTrigger = Dropdown.Trigger; export const DropdownPortal = Dropdown.Portal;
export function DropdownContent(props: Dropdown.DropdownMenuContentProps) { return <Dropdown.Content sideOffset={6} {...props} className={cn("z-[80] min-w-44 rounded-xl border border-border bg-surface p-1 shadow-xl", props.className)} />; }
export function DropdownItem(props: Dropdown.DropdownMenuItemProps) { return <Dropdown.Item {...props} className={cn("flex cursor-pointer items-center gap-2 rounded-lg px-3 py-2 text-sm outline-none hover:bg-surface-2 focus:bg-surface-2", props.className)} />; }
