"use client";

import Link from "next/link";
import { ArrowRight, Flame, Trophy } from "lucide-react";
import { ActivityCard } from "@/components/community/activity-card";
import { Card } from "@/components/ui/primitives";
import { PageHeader, UserAvatar } from "@/components/shared/shared";
import { initialChallenges, users } from "@/data/mock-data";
import { useAppStore } from "@/store/app-store";

export default function CommunityPage(){const activities=useAppStore(s=>s.activities);return <div className="page-wrap"><PageHeader title="Community" description="Celebrate progress, find momentum, and keep each other moving."/><div className="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_360px]"><div className="space-y-4">{activities.slice(0,12).map(a=><ActivityCard key={a.id} activity={a}/>)}</div><aside className="space-y-5"><Card className="p-5"><h2 className="mb-4 font-bold">Friends Activity</h2><div className="space-y-4">{users.slice(1,6).map((u,i)=><Link href={`/profile/${u.username}`} key={u.id} className="flex items-center gap-3"><UserAvatar user={u} size="sm"/><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{u.name}</div><div className="text-xs text-muted">{i%2?"Focused 25 minutes":"Checked in today"}</div></div><span className="h-2 w-2 rounded-full bg-success"/></Link>)}</div></Card><Card className="p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">Suggested Challenges</h2><Trophy className="h-4 w-4 text-primary"/></div>{initialChallenges.filter(c=>!c.joined).slice(0,3).map(c=><Link href={`/challenges/${c.id}`} key={c.id} className="group mb-2 flex items-center gap-3 rounded-xl bg-surface-2 p-3"><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{c.title}</div><div className="text-xs text-muted">{c.participants.toLocaleString()} joined</div></div><ArrowRight className="h-4 w-4 text-muted group-hover:text-primary"/></Link>)}</Card><Card className="p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">Top Streaks</h2><Flame className="h-4 w-4 fill-current text-primary"/></div>{[...users].sort((a,b)=>b.currentStreak-a.currentStreak).slice(0,5).map((u,i)=><div key={u.id} className="flex items-center gap-3 border-b border-border py-3 last:border-0"><span className="w-5 text-xs font-bold text-muted">{i+1}</span><UserAvatar user={u} size="sm"/><span className="flex-1 text-sm font-semibold">{u.name}</span><strong className="text-sm text-primary">{u.currentStreak}d</strong></div>)}</Card></aside></div></div>}
