"use client";

import { useState } from "react";
import { CalendarDays, Clock3, Flame, LayoutGrid, Plus, Target, Zap } from "lucide-react";
import { format } from "date-fns";
import { Button } from "@/components/ui/button";
import { Card, Progress } from "@/components/ui/primitives";
import { HabitCard } from "@/components/habits/habit-card";
import { HabitFormDialog } from "@/components/habits/habit-form";
import { ConsistencyHeatmap, WeeklyChart } from "@/components/dashboard/dashboard-charts";
import { ProgressRing, StatCard } from "@/components/shared/shared";
import { currentUser } from "@/data/mock-data";
import { useAppStore } from "@/store/app-store";

export default function DashboardPage(){const habits=useAppStore(s=>s.habits).filter(h=>!h.archived);const [formOpen,setFormOpen]=useState(false);const complete=habits.filter(h=>h.completedToday).length;const rate=Math.round(complete/habits.length*100);return <div className="page-wrap"><header className="mb-7 flex flex-col justify-between gap-4 pr-0 md:flex-row md:items-end md:pr-24"><div><p className="mb-1 text-sm font-semibold text-primary">Good morning</p><h1 className="text-3xl font-bold tracking-[-.04em] md:text-4xl">Ready to build momentum, Alex?</h1><p className="mt-2 text-muted">You’re on a {currentUser.currentStreak}-day streak. Keep it going.</p></div><div className="flex items-center gap-3"><span className="hidden items-center gap-2 text-sm text-muted sm:flex"><CalendarDays className="h-4 w-4"/>{format(new Date(),"EEEE, MMM d")}</span><Button onClick={()=>setFormOpen(true)}><Plus className="h-4 w-4"/>Quick add</Button></div></header>
  <div className="grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,.75fr)]"><Card className="p-5 md:p-6"><div className="mb-5 flex flex-col gap-5 sm:flex-row sm:items-center"><ProgressRing value={rate} size={128}><div><strong className="text-2xl">{complete}/{habits.length}</strong><div className="text-xs text-muted">complete</div></div></ProgressRing><div><div className="text-xs font-bold uppercase tracking-[.14em] text-primary">Today’s progress</div><h2 className="mt-1 text-2xl font-bold">{complete===habits.length?"Perfect day secured":"Keep the rhythm moving"}</h2><p className="mt-1 text-sm text-muted">{habits.length-complete} habits left. Your streak is safe after today’s check-ins.</p></div></div><div className="grid gap-3 lg:grid-cols-2">{habits.slice(0,5).map(h=><HabitCard habit={h} compact key={h.id}/>)}</div></Card>
  <div className="space-y-5"><Card className="overflow-hidden border-primary/25"><div className="bg-primary-soft p-5"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-primary text-white"><Flame className="h-6 w-6 fill-current"/></span><span className="rounded-full bg-warning-soft px-3 py-1 text-xs font-bold text-warning">3 hours left</span></div><div className="mt-5 text-3xl font-bold">12 Day Streak</div><p className="mt-1 text-sm text-muted">Longest: 34 days</p></div><div className="p-5"><div className="mb-3 grid grid-cols-7 gap-2 text-center text-[11px] font-bold text-muted">{"MTWTFSS".split("").map((d,i)=><span key={i}>{d}</span>)}</div><div className="grid grid-cols-7 gap-2">{[1,1,1,1,1,1,0].map((done,i)=><span key={i} className={`grid aspect-square place-items-center rounded-full text-xs font-bold ${done?"bg-primary text-white":i===6?"border-2 border-primary text-primary":"bg-surface-2 text-muted"}`}>{done?"✓":i===6?"•":""}</span>)}</div><div className="mt-4 flex items-center gap-2 rounded-lg bg-warning-soft px-3 py-2 text-xs font-semibold text-warning"><Clock3 className="h-4 w-4"/>Protect your streak before midnight.</div></div></Card><Card className="p-5"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Active challenges</p><p className="text-xs text-muted">2 check-ins need attention</p></div><Target className="h-5 w-5 text-primary"/></div><div className="mt-4 space-y-4">{[["30 Days of Reading",60],["Code Every Day",58]].map(([label,value])=><div key={String(label)}><div className="mb-1.5 flex justify-between text-xs"><span className="font-semibold">{label}</span><span className="text-muted">{value}%</span></div><Progress value={Number(value)}/></div>)}</div></Card></div></div>
  <div className="mt-5"><WeeklyChart/></div><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard icon={Target} label="Completion Rate" value="86%" note="+7% from last week" tone="success"/><StatCard icon={LayoutGrid} label="Total Habits" value="31" note="Across 7 active habits"/><StatCard icon={Clock3} label="Focus Time" value="6h 42m" note="12 sessions this week"/><StatCard icon={Zap} label="XP Earned" value="+480" note="550 XP to Level 9" tone="primary"/></div><div className="mt-5"><ConsistencyHeatmap/></div><HabitFormDialog open={formOpen} onOpenChange={setFormOpen}/></div>}
