"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Archive, CalendarCheck, Check, Clock3, Ellipsis, Flame, Pause, Percent, Trash2, Trophy } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Badge, Card, DropdownContent, DropdownItem, DropdownMenu, DropdownPortal, DropdownTrigger, Modal, Progress } from "@/components/ui/primitives";
import { DynamicIcon } from "@/components/shared/icon-map";
import { EmptyState, PageHeader, StatCard, StreakBadge } from "@/components/shared/shared";
import { HabitFormDialog } from "@/components/habits/habit-form";
import { useAppStore } from "@/store/app-store";

export function HabitDetail({id}:{id:string}){const habit=useAppStore(s=>s.habits.find(h=>h.id===id));const toggle=useAppStore(s=>s.toggleHabit);const archive=useAppStore(s=>s.archiveHabit);const remove=useAppStore(s=>s.deleteHabit);const notify=useAppStore(s=>s.notify);const [range,setRange]=useState("This month");const [edit,setEdit]=useState(false);const [confirm,setConfirm]=useState(false);const router=useRouter();const data=useMemo(()=>Array.from({length:range==="This week"?7:range==="This month"?16:24},(_,i)=>({day:i+1,rate:55+(i*17%44)})),[range]);if(!habit)return <div className="page-wrap"><EmptyState title="This habit is no longer available." description="It may have been deleted or you may not have permission to view it." action={<Button onClick={()=>router.push("/habits")}>Back to My Habits</Button>}/></div>;return <div className="page-wrap"><PageHeader title={habit.title} description={habit.description} action={<div className="flex gap-2"><Button variant={habit.completedToday?"secondary":"default"} onClick={()=>toggle(habit.id)}><Check className="h-4 w-4"/>{habit.completedToday?"Undo today":"Complete Habit"}</Button><DropdownMenu><DropdownTrigger asChild><Button variant="secondary" size="icon" aria-label="Habit actions"><Ellipsis className="h-4 w-4"/></Button></DropdownTrigger><DropdownPortal><DropdownContent align="end"><DropdownItem onSelect={()=>setEdit(true)}>Edit habit</DropdownItem><DropdownItem onSelect={()=>notify("Habit paused. Reminders are off.") }><Pause className="h-4 w-4"/>Pause habit</DropdownItem><DropdownItem onSelect={()=>archive(habit.id)}><Archive className="h-4 w-4"/>{habit.archived?"Restore habit":"Archive habit"}</DropdownItem><DropdownItem onSelect={()=>setConfirm(true)} className="text-danger"><Trash2 className="h-4 w-4"/>Delete habit</DropdownItem></DropdownContent></DropdownPortal></DropdownMenu></div>}/><Card className="mb-5 flex flex-col gap-6 overflow-hidden p-5 sm:flex-row sm:items-center"><span className="grid h-20 w-20 shrink-0 place-items-center rounded-2xl" style={{background:`${habit.color}18`,color:habit.color}}><DynamicIcon name={habit.icon} className="h-9 w-9"/></span><div className="flex-1"><div className="flex flex-wrap gap-2"><Badge>{habit.category}</Badge><Badge>{habit.frequency}</Badge><Badge>{habit.visibility}</Badge></div><div className="mt-4 flex flex-wrap items-end gap-x-8 gap-y-3"><div><div className="text-xs text-muted">Current streak</div><StreakBadge days={habit.currentStreak}/></div><div><div className="text-xs text-muted">Best streak</div><strong>{habit.bestStreak} days</strong></div><div><div className="text-xs text-muted">Completion</div><strong>{habit.completionRate}%</strong></div></div></div><div className="w-full sm:w-48"><div className="mb-2 flex justify-between text-xs"><span>This month</span><strong>{habit.completionRate}%</strong></div><Progress value={habit.completionRate}/></div></Card>
  <Card className="mb-5 p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">Completion history</h2><p className="text-xs text-muted">Your check-ins over time</p></div><div className="flex rounded-lg bg-surface-2 p-1">{["This week","This month","All time"].map(v=><button key={v} onClick={()=>setRange(v)} className={`rounded-md px-2.5 py-1 text-xs font-semibold ${range===v?"bg-surface shadow-sm":"text-muted"}`}>{v}</button>)}</div></div><div className="h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{left:-24,right:6}}><defs><linearGradient id="habitArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={habit.color} stopOpacity={.3}/><stop offset="100%" stopColor={habit.color} stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{fontSize:11,fill:"var(--muted)"}}/><YAxis domain={[0,100]} axisLine={false} tickLine={false} tick={{fontSize:11,fill:"var(--muted)"}}/><Tooltip contentStyle={{background:"var(--surface)",border:"1px solid var(--border)",borderRadius:10}}/><Area dataKey="rate" type="monotone" stroke={habit.color} strokeWidth={2.5} fill="url(#habitArea)"/></AreaChart></ResponsiveContainer></div></Card>
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard icon={CalendarCheck} label="Total completions" value="146" note="Since you started"/><StatCard icon={Flame} label="Current streak" value={`${habit.currentStreak} days`} tone="primary"/><StatCard icon={Trophy} label="Best streak" value={`${habit.bestStreak} days`}/><StatCard icon={Percent} label="Completion rate" value={`${habit.completionRate}%`} tone="success"/></div><Card className="mt-5 p-5"><h2 className="mb-4 font-bold">Recent Activity</h2><div className="divide-y divide-border">{["Aug 18","Aug 17","Aug 16","Aug 15","Aug 14"].map((date,i)=><div key={date} className="flex items-center gap-3 py-3"><span className={`grid h-8 w-8 place-items-center rounded-full ${i===4?"bg-surface-2 text-muted":"bg-success-soft text-success"}`}>{i===4?<Clock3 className="h-4 w-4"/>:<Check className="h-4 w-4"/>}</span><span className="flex-1 text-sm"><strong>{date}</strong> — {i===4?"Missed":"Completed"}</span><span className="text-xs text-muted">{i===0?"8:12 AM":""}</span></div>)}</div></Card><HabitFormDialog open={edit} onOpenChange={setEdit} habit={habit}/><Modal open={confirm} onOpenChange={setConfirm} title={`Delete ${habit.title}?`} description="This removes the habit and its history from this demo. This action cannot be undone."><div className="flex justify-end gap-3"><Button variant="ghost" onClick={()=>setConfirm(false)}>Cancel</Button><Button variant="danger" onClick={()=>{remove(habit.id);setConfirm(false);router.push("/habits")}}><Trash2 className="h-4 w-4"/>Delete Habit</Button></div></Modal></div>}
