"use client";

import { useState } from "react";
import { Bell, BookOpen, Brain, Code2, Droplets, Footprints, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input, Label, Modal, Select, Switch, Textarea } from "@/components/ui/primitives";
import { useAppStore } from "@/store/app-store";
import type { Category, CreateHabitInput, Habit, Visibility } from "@/types";

const categories: Category[]=["Health","Learning","Fitness","Mindfulness","Productivity","Other"];
const iconOptions=[{name:"Footprints",icon:Footprints},{name:"BookOpen",icon:BookOpen},{name:"Droplets",icon:Droplets},{name:"Code2",icon:Code2},{name:"Brain",icon:Brain}];
const colors=["#f9734f","#8b5cf6","#0ea5e9","#14b8a6","#22c55e","#ec4899","#f59e0b"];
const defaults:CreateHabitInput={title:"",description:"",icon:"Footprints",color:colors[0],category:"Fitness",frequency:"Every day",goalType:"completion",visibility:"Private"};
export function HabitFormDialog({open,onOpenChange,habit}:{open:boolean;onOpenChange:(v:boolean)=>void;habit?:Habit}){
  if(!open)return null;
  return <HabitFormDialogInner open={open} onOpenChange={onOpenChange} habit={habit}/>;
}

function HabitFormDialogInner({open,onOpenChange,habit}:{open:boolean;onOpenChange:(v:boolean)=>void;habit?:Habit}){
  const initial:CreateHabitInput=habit?{title:habit.title,description:habit.description,icon:habit.icon,color:habit.color,category:habit.category,frequency:habit.frequency,reminder:habit.reminder,goalType:habit.goalType,goalValue:habit.goalValue,goalUnit:habit.goalUnit,visibility:habit.visibility}:defaults;
  const add=useAppStore(s=>s.addHabit);const update=useAppStore(s=>s.updateHabit);const [form,setForm]=useState<CreateHabitInput>(initial);const [reminder,setReminder]=useState(Boolean(habit?.reminder));const [days,setDays]=useState<string[]>([]);
  const change=<K extends keyof CreateHabitInput>(key:K,value:CreateHabitInput[K])=>setForm(f=>({...f,[key]:value})); const valid=form.title.trim().length>=2 && (form.goalType==="completion" || Number(form.goalValue)>0);
  const submit=(e:React.FormEvent)=>{e.preventDefault();const value={...form,frequency:form.frequency==="Specific days"&&days.length?days.join(", "):form.frequency,reminder:reminder?(form.reminder||"09:00"):undefined};if(habit)update(habit.id,value);else add(value);onOpenChange(false)};
  return <Modal open={open} onOpenChange={onOpenChange} title={habit?"Edit habit":"Create a new habit"} description="Make the action specific enough that checking in feels obvious."><form onSubmit={submit} className="space-y-5"><div><Label htmlFor="habit-name">Habit name</Label><Input id="habit-name" value={form.title} onChange={e=>change("title",e.target.value)} placeholder="e.g. Read 20 minutes" required minLength={2}/>{form.title.length===1&&<p className="mt-1 text-xs text-danger">Use at least 2 characters.</p>}</div><div><Label htmlFor="habit-description">Description <span className="font-normal text-muted">(optional)</span></Label><Textarea id="habit-description" value={form.description} onChange={e=>change("description",e.target.value)} placeholder="Why does this habit matter?"/></div>
  <div className="grid gap-4 sm:grid-cols-2"><div><Label>Icon</Label><div className="flex gap-2">{iconOptions.map(item=><button type="button" key={item.name} onClick={()=>change("icon",item.name)} aria-label={item.name} className={`grid h-10 w-10 place-items-center rounded-lg border ${form.icon===item.name?"border-primary bg-primary-soft text-primary":"bg-background text-muted"}`}><item.icon className="h-4 w-4"/></button>)}</div></div><div><Label>Color</Label><div className="flex gap-2">{colors.map(color=><button type="button" key={color} onClick={()=>change("color",color)} aria-label={`Choose ${color}`} className={`h-8 w-8 rounded-full ${form.color===color?"ring-2 ring-primary ring-offset-2 ring-offset-surface":""}`} style={{background:color}}/>)}</div></div></div>
  <div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="habit-category">Category</Label><Select id="habit-category" value={form.category} onChange={e=>change("category",e.target.value as Category)}>{categories.map(c=><option key={c}>{c}</option>)}</Select></div><div><Label htmlFor="habit-frequency">Frequency</Label><Select id="habit-frequency" value={form.frequency.includes(",")?"Specific days":form.frequency} onChange={e=>change("frequency",e.target.value)}><option>Every day</option><option>Specific days</option><option>3 times per week</option><option>Weekdays</option><option>Custom</option></Select></div></div>
  {form.frequency==="Specific days"&&<div><Label>Repeat on</Label><div className="flex flex-wrap gap-2">{"MTWTFSS".split("").map((d,i)=><button type="button" key={i} onClick={()=>setDays(v=>v.includes(`${d}${i}`)?v.filter(x=>x!==`${d}${i}`):[...v,`${d}${i}`])} className={`h-9 w-9 rounded-full border text-xs font-bold ${days.includes(`${d}${i}`)?"border-primary bg-primary text-white":"bg-background"}`}>{d}</button>)}</div></div>}
  <div className="rounded-xl border border-border p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><Bell className="h-4 w-4 text-muted"/><div><div className="font-semibold">Reminder</div><div className="text-xs text-muted">Get a gentle nudge at the right time.</div></div></div><Switch checked={reminder} onCheckedChange={setReminder} label="Enable reminder"/></div>{reminder&&<div className="mt-4"><Label htmlFor="reminder-time">Time</Label><Input id="reminder-time" type="time" value={form.reminder||"09:00"} onChange={e=>change("reminder",e.target.value)}/></div>}</div>
  <div><Label htmlFor="goal-type">Goal type</Label><Select id="goal-type" value={form.goalType} onChange={e=>change("goalType",e.target.value as Habit["goalType"])}><option value="completion">Checkbox / completion</option><option value="duration">Duration</option><option value="quantity">Quantity</option></Select></div>{form.goalType!=="completion"&&<div className="grid grid-cols-2 gap-3"><div><Label htmlFor="goal-value">Goal</Label><Input id="goal-value" type="number" min="1" value={form.goalValue||""} onChange={e=>change("goalValue",Number(e.target.value))} placeholder="20"/></div><div><Label htmlFor="goal-unit">Unit</Label><Input id="goal-unit" value={form.goalUnit||""} onChange={e=>change("goalUnit",e.target.value)} placeholder={form.goalType==="duration"?"minutes":"glasses"}/></div></div>}
  <div><Label htmlFor="visibility">Visibility</Label><Select id="visibility" value={form.visibility} onChange={e=>change("visibility",e.target.value as Visibility)}><option>Private</option><option>Friends</option><option>Public</option></Select></div><div className="flex justify-end gap-3 border-t border-border pt-5"><Button type="button" variant="ghost" onClick={()=>onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={!valid}><Plus className="h-4 w-4"/>{habit?"Save changes":"Create Habit"}</Button></div></form></Modal>;
}
